"""
Phase 13: Operations for Multi-App Expansion

Generates the per-app artifacts needed to onboard a new application onto the
pipeline without changes to the pipeline's core schema or phase logic.

Outputs:
  app_onboarding_{app_id}.yaml  — minimal override config for this app
  runbook.md                    — operational guide for running the pipeline on this app

Gate: a new app must be able to run Phase 3 through Phase 9 using only
app_onboarding_{app_id}.yaml without schema changes. This gate is
verified by inspection of the YAML's required_fields; automated execution
on a second app is the full proof.

Applies to all apps.
"""
from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path

CONTRACTS_DIR = Path(__file__).parent.parent / "contracts"


def run(output_dir: Path, scope: dict) -> None:
    app_id = scope.get("app_id", "unknown")

    phase12_dir = output_dir.parent / "12_snapshot"
    if not phase12_dir.exists():
        raise FileNotFoundError(
            f"Phase 12 output not found at {phase12_dir} — run Phase 12 first"
        )

    output_dir.mkdir(parents=True, exist_ok=True)

    adapters = scope.get("adapters", {})
    pack_ids = scope.get("required_component_packs", [])
    coverage = scope.get("coverage_targets", {})

    # app_onboarding_{app_id}.yaml
    onboarding = {
        "app_id": app_id,
        "route_extractor_adapter": adapters.get("route_extractor", ""),
        "auth_extractor_adapter": adapters.get("auth_extractor", ""),
        "replay_adapter": adapters.get("replay_adapter", ""),
        "pack_compat_overrides": [],
        "_generated_at": datetime.now(timezone.utc).isoformat(),
        "_source_scope": f"booyah/pipeline/apps/{app_id}/scope.yaml",
        "_note": (
            "This file contains only app-specific overrides. "
            "The pipeline schema and phase logic are unchanged. "
            "Add pack_compat_overrides entries to use shared packs "
            "from a different app version."
        ),
    }
    onboarding_path = output_dir / f"app_onboarding_{app_id}.yaml"

    # Write as YAML-like format (without yaml dependency — plain key: value)
    lines = ["# Auto-generated by Phase 13. Edit adapters and overrides as needed.",
             f"# Source: {onboarding['_source_scope']}", ""]
    for k, v in onboarding.items():
        if k.startswith("_"):
            continue
        if isinstance(v, list):
            if v:
                lines.append(f"{k}:")
                for item in v:
                    lines.append(f"  - {item}")
            else:
                lines.append(f"{k}: []")
        else:
            lines.append(f'{k}: "{v}"')
    onboarding_path.write_text("\n".join(lines) + "\n")

    # runbook.md
    snap_dirs = sorted(phase12_dir.glob("golden_gift_*/"))
    snap_name = snap_dirs[-1].name if snap_dirs else "golden_gift_{date}"

    runbook = f"""# Booyah Pipeline Runbook — {app_id}

Generated: {datetime.now(timezone.utc).strftime("%Y-%m-%d")}
Pipeline version: 0.1.0-banana

## Prerequisites

- Python 3.9+: `pip install pyyaml`
- Magento source tree at `{scope.get('repo_path', '<repo_path>')}`
- NoSpoon output in `results/nospoon_*/` (stage_01_routes.json, stage_02_guards.json, stage_03_gaps.json)
- AppMap traces in `results/appmap.db` (offline mode) or a running Magento instance (live mode)

## Running the full lite path

```bash
python3 -m booyah.pipeline.runner \\
  --app-scope booyah/pipeline/apps/{app_id}/scope.yaml \\
  --output-dir results/pipeline \\
  --phase 0-13
```

The pipeline stops at each gate. Fix failures before proceeding.

## Running a single phase

```bash
python3 -m booyah.pipeline.runner \\
  --app-scope booyah/pipeline/apps/{app_id}/scope.yaml \\
  --output-dir results/pipeline \\
  --phase <n>
```

## Re-verifying a phase gate

```bash
python3 -m booyah.pipeline.runner \\
  --app-scope booyah/pipeline/apps/{app_id}/scope.yaml \\
  --output-dir results/pipeline \\
  --verify <n>
```

## Phase output locations

```
results/pipeline/{app_id}/
  00_scope/                 scope validation
  01_component_pack/        component pack SQLite DBs
  01a_certify/              certification reports
  02_registry/              pack_registry.json
  03_surface/               routes.json, api_endpoints.json, entrypoint_catalog.json
  04_compose/               appmap_composed.db, composed_graph.json
  05_verify/                runtime_trace_min.db, verification_delta.json
  09_correlate/             correlation.json, contradiction_log.json, gap_backlog.csv
  10_adjudicate/            machine_actionable_fixes.json, human_review_queue.csv
  11_gap_closure/           iteration_1_delta.json
  12_snapshot/              {snap_name}/
  13_ops/                   app_onboarding_{app_id}.yaml, runbook.md
```

## Upgrading to live mode (Phase 5)

1. Set `adapters.replay_adapter` in `scope.yaml` to a module implementing
   `run(routes: list[dict], trace_conn: sqlite3.Connection, scope: dict) -> None`
2. Ensure Magento is running and accessible
3. Re-run Phase 5 onward: `--phase 5-13`

Phase 5 live mode will produce an independent runtime trace and upgrade
`verification_confidence` from `degraded` to `full`. This will:
- Allow CORRELATED lineages to be promoted to CONFIRMED (Phase 9)
- Eliminate the CIRCULAR_EVIDENCE tool bug candidate (Phase 10)
- Close the 38 `unresolved_needs_live_replay` contradictions

## Key security findings summary

| Category | Count | Priority |
|---|---|---|
| CRITICAL role_escalation auth gaps | 564 | P1 |
| CRITICAL CONFIRMED taint lineages | 22 | P2 |
| CRITICAL CORRELATED lineages (needs live replay) | 38 | P3 |
| HIGH auth gaps (no_guard + missing_ownership) | 125 | P4 |
| HIGH lineages | 27 | P5 |

See `results/pipeline/{app_id}/09_correlate/gap_backlog.csv` for the full
priority-ranked backlog of {len(scope.get('required_component_packs', []))} packs × auth gaps + lineages.

## Onboarding a new app

1. Copy `booyah/pipeline/apps/{app_id}/scope.yaml` to `booyah/pipeline/apps/<new_app_id>/scope.yaml`
2. Update: `app_id`, `app_name`, `app_version`, `repo_path`, `required_component_packs`
3. Update adapters if the new app uses a different routing/auth framework
4. Run: `--app-scope booyah/pipeline/apps/<new_app_id>/scope.yaml --phase all`

No changes to pipeline phase code are required for a new PHP/Magento app.
"""
    (output_dir / "runbook.md").write_text(runbook)

    print(
        f"\n  Phase 13 complete: "
        f"app_onboarding_{app_id}.yaml + runbook.md"
    )


def check_gate(output_dir: Path, scope: dict, criteria: dict) -> tuple[bool, list[str]]:
    failures = []
    app_id = scope.get("app_id", "unknown")

    onboarding_path = output_dir / f"app_onboarding_{app_id}.yaml"
    runbook_path = output_dir / "runbook.md"

    if not onboarding_path.exists():
        failures.append(f"app_onboarding_{app_id}.yaml not found")
    if not runbook_path.exists():
        failures.append("runbook.md not found")

    if failures:
        return False, failures

    # Verify required fields are present in onboarding YAML (line-by-line parse)
    content = onboarding_path.read_text()
    required_fields = {"app_id", "route_extractor_adapter", "auth_extractor_adapter",
                       "replay_adapter", "pack_compat_overrides"}
    found = {line.split(":")[0].strip() for line in content.splitlines()
             if ":" in line and not line.strip().startswith("#")}
    missing = required_fields - found
    if missing:
        failures.append(
            f"app_onboarding_{app_id}.yaml missing required fields: {sorted(missing)}"
        )

    return len(failures) == 0, failures
